### ISSUE TITLE
Filter out tombstones during replication 

### ISSUE THREAD

**Issue by garbados** [neighbourhoodie/couch-continuum#17]
<strike>There are use cases where one would want to regenerate a database without modifying its Q value, such as to deal with deleted documents. Should Q be made an optional parameter to handle this case?</strike>

Databases are sometimes migrated to remove tombstones, but this requires filtering them out. The tool should filter tombstones when creating replicas, so that the regenerated primary does not contain them.

**Comment by wohali** [comment]
But replicating back and forth WILL work if you use a filtered replication.

**Comment by janl** [comment]
Right, that would make a great option + addition to this.

**Comment by garbados** [comment]
Added in PR #25
