### ISSUE TITLE
Change q and/or n of the "special" databases

### ISSUE THREAD

**Issue by sblaisot** [neighbourhoodie/couch-continuum#48]
Is it possible with couchdb-continuum to change `q` or `n` of the "special" databases like `_global_changes` ?

I tried with `couch-continuum -N _global_changes -q 1 -n 3 -u http://user:pass@couch-01:5984` but all I got is
```
[couch-continuum] Migrating database '_global_changes'...
[couch-continuum] ERROR
[couch-continuum] Unexpected error: {"error":"illegal_database_name","reason":"Name: '_global_changes_temp_copy'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}
```

is there a magic trick to update "special" databases `q` or `n` ?

**Comment by janl** [comment]
https://github.com/neighbourhoodie/couch-continuum/pull/49 should fix this

**Comment by sblaisot** [comment]
ok, I can see how #49 could help when dealing with temporary db creation, but, as far as I understand it, in the second part, the original database will get destroyed/recreated and I'm afraid couch-continuum will be unable to recreate it with the same name starting with `_` right ?

**Comment by garbados** [comment]
System databases are whitelisted to be re-created with an underscore, so the continuum recreated them OK. :)

For example:

```bash
$ couch-continuum -N _users
[couch-continuum] Replicating localhost:5984/_users to localhost:5984/temp_copy__users
[couch-continuum] (====================) 100% 0.0s
Ready to replace the primary with the replica. Continue? [y/N] y
[couch-continuum] Recreating primary localhost:5984/_users
[couch-continuum] (====================) 100% 0.0s
[couch-continuum] Replicating localhost:5984/temp_copy__users to localhost:5984/_users
[couch-continuum] (====================) 100% 0.0s

Migrated database: localhost:5984/_users
```
