### ISSUE TITLE
Migrate-all requires source parameter

### ISSUE THREAD

**Issue by shammond42** [neighbourhoodie/couch-continuum#55]
When I try to use migrate-all via the follow command, I get the error "Missing required argument: source."

couch-continuum migrate-all -u http://user:passwd@10.0.42.24:5984 -v -q 1

I tried adding one of my databases as a source and that produced this error.

Unexpected error: {"generatedMessage":false,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":16,"operator":"==="}

Thanks!

**Comment by janl** [comment]
same here cc @garbados

**Comment by garbados** [comment]
Weird! I'm on it.
