### ISSUE TITLE
Unexpected error: {"generatedMessage":false,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="}

### ISSUE THREAD

**Issue by cosar-pp** [neighbourhoodie/couch-continuum#64]
Hello,

i change the q from 8 to 1. This works for some databases but not for some databases:
/bin/couch-continuum -N http://admin:XXX@127.0.0.1:5984/iq_published_cc_acc -u http://admin:XXX@127.0.0.1:5984 -q 1 -n 3 -v

[couch-continuum] Created new continuum: {
  "filterTombstones": false,
  "interval": 1000,
  "n": 3,
  "q": 1,
  "replicateSecurity": true,
  "source": "127.0.0.1:5984/iq_published_cc_acc",
  "target": "127.0.0.1:5984/temp_copy_iq_published_cc_acc",
  "url": "127.0.0.1:5984"
}
[couch-continuum] Migrating database: 127.0.0.1:5984undefined
[couch-continuum] Creating replica 127.0.0.1:5984/temp_copy_iq_published_cc_acc...
[couch-continuum] [0/5] Checking if primary is in use...
[couch-continuum] [1/5] Creating replica db: 127.0.0.1:5984/temp_copy_iq_published_cc_acc
[couch-continuum] [2/5] Beginning replication of primary to replica...
[couch-continuum] Replicating 127.0.0.1:5984/iq_published_cc_acc to 127.0.0.1:5984/temp_copy_iq_published_cc_acc
[couch-continuum] Replicating http://admin:XXX@127.0.0.1:5984/iq_published_cc_acc/_security to http://admin:XXX@127.0.0.1:5984/temp_copy_iq_published_cc_acc...
[couch-continuum] [3/5] Verifying primary did not change during replication...
ERROR
Unexpected error: {"generatedMessage":false,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="}

Any idea?
Cosar

**Comment by janl** [comment]
it looks like your database received updates while `couch-continuum` ran. Step 3 validates that there were no writes to the source while preparing the temporary target, and that step fails. Can you make sure no updates (including doc creates updates and deletes) happen on the source db? This is to ensure that no data is lost.

**Comment by cosar-pp** [comment]
i'm not sure, this is actually a not used cluster, can i run couch-continuum when i set the database in maintenance_mode?

**Comment by janl** [comment]
that doesn’t work, couch-continuum still needs to make normal requests.

**Comment by janl** [comment]
if you watch the update_seq for the database in question, do you see it going up while couch_continuum is running?

**Comment by cosar-pp** [comment]
second run was successful for the db iq_published_cc_acc. But i tried the on the DB iq_published_cc_acc%2Fresources
update_seq is the same before and after running continuum. I still get the error:

/bin/couch-continuum -N http://admin:XXX@127.0.0.1:5984/iq_published_cc_acc%2Fresources -u http://admin:XXX@127.0.0.1:5984 -q 1 -n 3
[couch-continuum] Replicating 127.0.0.1:5984/iq_published_cc_acc%2Fresources to 127.0.0.1:5984/temp_copy_iq_published_cc_acc%2Fresources
[couch-continuum] (====================) 100% 0.0s
ERROR
Unexpected error: {"generatedMessage":false,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="}

**Comment by janl** [comment]
and have you verified that the update_seq for that db didn’t change while couch-continuum was running?

**Comment by cosar-pp** [comment]
yes, before:
"db_name": "iq_published_cc_acc/resources",
  "update_seq": "2-g1AAAAJLeJzLYWBg4MhgTmEwSM4vTc5ISXIoLU4tKtaF8nQNjHQL8pN103P1gKggsyI1pyCxKFsvL7UkB6iTKZEhSf7___9ZiQz4zDDEa0aSApBMsqfYGAeQMfGEjTHGb0wCyJh6sDFM5LsmjwVIMjQAKaBJ8wm4CH8YQ4xaADFqP0VhBDHqAMSo-1Qw6gHEKFCQZwEAyRvHNA",

and after:
  "db_name": "iq_published_cc_acc/resources",
  "update_seq": "2-g1AAAAJLeJzLYWBg4MhgTmEwSM4vTc5ISXIoLU4tKtaF8nQNjHQL8pN103P1gKggsyI1pyCxKFsvL7UkB6iTKZEhSf7___9ZiQz4zDDEa0aSApBMsqfYGAeQMfGEjTHGb0wCyJh6sDFM5LsmjwVIMjQAKaBJ8wm4CH8YQ4xaADFqP0VhBDHqAMSo-1Qw6gHEKFCQZwEAyRvHNA",

**Comment by janl** [comment]
the latest error message doesn’t include the line `[couch-continuum] [3/5] Verifying primary did not change during replication...` from your original log. That suggests there is a problem with the replication. Check the couch log for hints

**Comment by cosar-pp** [comment]
it was successful. May be the GET requests cause the errors?

[couch-continuum] Replicating 127.0.0.1:5984/iq_published_cc_acc%2Fresources to 127.0.0.1:5984/temp_copy_iq_published_cc_acc%2Fresources
[couch-continuum] (====================) 100% 0.0s

Ready to replace the primary with the replica. Continue? [y/N] y
[couch-continuum] Recreating primary 127.0.0.1:5984/iq_published_cc_acc%2Fresources
[couch-continuum] (====================) 100% 0.0s
[couch-continuum] Replicating 127.0.0.1:5984/temp_copy_iq_published_cc_acc%2Fresources to 127.0.0.1:5984/iq_published_cc_acc%2Fresources
[couch-continuum] (====================) 100% 0.0s
Migrated database: 127.0.0.1:5984undefined

**Comment by cosar-pp** [comment]
Thank you for helping

**Comment by janl** [comment]
glad it worked.

**Comment by janl** [comment]
cc @garbados the error messages here could be a bit more user-friendly ;)

**Comment by garbados** [comment]
That `Migrating database: 127.0.0.1:5984undefined` has me nervous. I'll file an issue on it, and the error messages.
